### ISSUE TITLE
Key bindings don't work anymore since last update

### ISSUE THREAD

**Issue by clovissix** [Scordium/Rearchitector#1]
Since the 12/05 update my key bindings don't work anymore for this plugin. I tried change them to numpad keys, but to no avail.

**Comment by clovissix** [comment]
Z-axis seems to work, but not Y and X

**Comment by Scordium** [comment]
Shift/Ctrl/Alt + Numpad do not work on windows.
https://devblogs.microsoft.com/oldnewthing/20040906-00/?p=37953
Other than that i can't help you, check for other mods using the same keybinds.
